version: "3"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: "npm start"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  node_modules: